import Head from "next/head";
import { Box, Container, Heading, SlideFade } from "@chakra-ui/react";
import Paragraph from "../components/Paragraph";

const About = () => {
  return (
    <div>
      <Head>
        <title>About | Meer Bahadin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container maxW="container.lg" mt={10}>
          <SlideFade in={true} offsetY={80}>
            <Box>
              <Heading
                as="h1"
                fontSize={{ base: "28px", md: "40px", lg: "48px" }}
                mb={4}
              >
                About Me
              </Heading>
              <Paragraph fontSize="2xl" lineHeight={1.6}>
                Full stack developer - UI / UX Designer, focused on Javascript,{" "}
                Nodejs React . I work as a full stack developer. You’ve found my
                personal website on the internet
              </Paragraph>
            </Box>
          </SlideFade>
        </Container>
      </main>
    </div>
  );
};

export default About;
