import Head from 'next/head';
import {
  Box,
  Container,
  Heading,
  SlideFade,
  Link,
  Divider,
  Grid,
  LightMode,
  IconButton,
  Button,
  ButtonGroup,
} from '@chakra-ui/react';

import {
  FaEnvelope,
  FaWhatsapp,
  FaNodeJs,
  FaReact,
  FaJs,
  FaDatabase,
  FaGitAlt,
  FaFigma,
} from 'react-icons/fa';

import Paragraph from '../components/Paragraph';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Meer Bahadin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container maxW="container.lg" mt={10}>
          <SlideFade in={true} offsetY={80}>
            <Box>
              <Heading
                as="h1"
                fontSize={{ base: '28px', md: '40px', lg: '48px' }}
                mb={3}
              >
                Hey , I’m Meer Bahadin
              </Heading>
              <Paragraph fontSize="2xl" lineHeight={1.6}>
                Full stack developer - UI / UX Designer, focused on Javascript,{' '}
                <Link
                  color="green.300"
                  href="https://www.nodejs.org"
                  isExternal
                  fontWeight="700"
                >
                  Nodejs,
                </Link>{' '}
                <Link
                  color="green.300"
                  href="https://www.reactjs.org"
                  fontWeight="700"
                  isExternal
                >
                  React
                </Link>
                . I work as a full stack developer. You’ve found my personal
                website on the internet.
              </Paragraph>
              <Box mt={10}>
                <LightMode>
                  <ButtonGroup>
                    <Button
                      colorScheme="green"
                      bg="green.500"
                      href="mailto:info@meera.dev"
                      borderRadius={5}
                      p={3}
                      as="a"
                      leftIcon={<FaEnvelope />}
                    >
                      info@meera.dev
                    </Button>
                    <Button
                      colorScheme="green"
                      bg="green.500"
                      href="mailto:info@meera.dev"
                      borderRadius={5}
                      p={3}
                      as="a"
                      leftIcon={<FaWhatsapp />}
                    >
                      WhatsApp
                    </Button>
                  </ButtonGroup>
                </LightMode>
              </Box>
              <Divider my={10} />
            </Box>
          </SlideFade>
          <SlideFade in={true} offsetY={80} delay={0.2}>
            <Heading
              as="h1"
              fontSize={{ base: '24px', md: '30px', lg: '36px' }}
              mb={3}
            >
              Primary Stack & Technologies
            </Heading>
            <Paragraph fontSize="xl" lineHeight={1.6}>
              As a full-stack web developer there are alot of tools you use in
              your daily bases, these are primary tools that i use & like.
            </Paragraph>
            <Grid
              mt={10}
              templateColumns={[
                '1fr',
                '1fr',
                'repeat(2, 1fr)',
                'repeat(3, 1fr)',
              ]}
              gap={5}
            >
              <Box
                w="100%"
                p={4}
                borderColor="gray.700"
                borderRadius={5}
                borderWidth="1px"
                transition=".5s"
                d="flex"
                _hover={{
                  borderColor: 'green.300',
                }}
              >
                <IconButton
                  as="a"
                  href="#"
                  mr={3}
                  aria-label="NodeJs"
                  icon={<FaNodeJs fontSize="20px" />}
                />
                <Box>
                  <Heading as="h6" size="sm">
                    NodeJs
                  </Heading>
                  <Paragraph mt={1} fontSize="sm">
                    Chrome's V8 JavaScript engine for server-side javascript.
                  </Paragraph>
                </Box>
              </Box>
              <Box
                w="100%"
                p={4}
                borderColor="gray.700"
                borderColor="gray.700"
                borderRadius={5}
                borderWidth="1px"
                transition=".5s"
                d="flex"
                _hover={{
                  borderColor: 'green.300',
                }}
              >
                <IconButton
                  as="a"
                  href="#"
                  mr={3}
                  aria-label="Javascript"
                  icon={<FaJs fontSize="20px" />}
                />
                <Box>
                  <Heading as="h6" size="sm">
                    Javascript
                  </Heading>
                  <Paragraph mt={1} fontSize="sm">
                    These days you can't build an amazing product without JS.
                  </Paragraph>
                </Box>
              </Box>
              <Box
                w="100%"
                p={4}
                borderColor="gray.700"
                borderRadius={5}
                borderWidth="1px"
                transition=".5s"
                d="flex"
                _hover={{
                  borderColor: 'green.300',
                }}
              >
                <IconButton
                  as="a"
                  href="#"
                  aria-label="Github"
                  mr={3}
                  icon={<FaReact fontSize="20px" />}
                />
                <Box>
                  <Heading as="h6" size="sm">
                    ReactJs
                  </Heading>
                  <Paragraph mt={1} fontSize="sm">
                    A JavaScript library for building user interfaces.
                  </Paragraph>
                </Box>
              </Box>
              <Box
                w="100%"
                p={4}
                borderColor="gray.700"
                borderRadius={5}
                borderWidth="1px"
                transition=".5s"
                d="flex"
                role="group"
                _hover={{
                  borderColor: 'green.300',
                }}
              >
                <IconButton
                  as="a"
                  href="#"
                  aria-label="Github"
                  mr={3}
                  _groupHover={{ color: 'green.300' }}
                  icon={<FaDatabase fontSize="20px" />}
                />
                <Box>
                  <Heading as="h6" size="sm">
                    SQL & MongoDb
                  </Heading>
                  <Paragraph mt={1} fontSize="sm">
                    Both database are great, and they have their use cases.
                  </Paragraph>
                </Box>
              </Box>
              <Box
                w="100%"
                p={4}
                borderColor="gray.700"
                borderRadius={5}
                borderWidth="1px"
                transition=".5s"
                d="flex"
                _hover={{
                  borderColor: 'green.300',
                }}
              >
                <IconButton
                  as="a"
                  href="#"
                  mr={3}
                  aria-label="Github"
                  icon={<FaGitAlt fontSize="20px" />}
                />
                <Box>
                  <Heading as="h6" size="sm">
                    GIT & Github
                  </Heading>
                  <Paragraph mt={1} fontSize="sm">
                    A version control system that gives you a lot of
                    flexibility.
                  </Paragraph>
                </Box>
              </Box>
              <Box
                w="100%"
                p={4}
                borderColor="gray.700"
                borderRadius={5}
                borderWidth="1px"
                transition=".5s"
                d="flex"
                _hover={{
                  borderColor: 'green.300',
                }}
              >
                <IconButton
                  as="a"
                  href="#"
                  aria-label="Figma"
                  mr={3}
                  icon={<FaFigma fontSize="20px" />}
                />
                <Box>
                  <Heading as="h6" size="sm">
                    Figma
                  </Heading>
                  <Paragraph mt={1} fontSize="sm">
                    Figma is powerfull & easy to use software for UI/UX design.
                  </Paragraph>
                </Box>
              </Box>
            </Grid>
          </SlideFade>
        </Container>
      </main>
    </div>
  );
}
